# Generated by Django 3.2.4 on 2021-07-06 13:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedCVE',
            fields=[
                ('cve_id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('added_by', models.CharField(default='Anonymous', max_length=40)),
                ('date', models.DateField(default=datetime.date.today)),
                ('reason', models.CharField(choices=[('accepted', 'Risk accepted'), ('notapplicable', 'Not applicable'), ('unfixed', 'Editor will not fix')], default='accepted', max_length=13)),
                ('comment', models.TextField(default='')),
            ],
        ),
    ]
