# Generated by Django 3.2.4 on 2021-07-06 14:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_listing', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedcve',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='allowedcve',
            name='cve_id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False, validators=[django.core.validators.RegexValidator(message='Invalid CVE ID format', regex='^CVE-\\d{4}-\\d{4,11}$')]),
        ),
    ]
