# Generated by Django 3.2.6 on 2021-08-03 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cve_listing', '0002_auto_20210706_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedcve',
            name='reason',
            field=models.CharField(choices=[('accepted', 'Risk accepted'), ('notapplicable', 'Not applicable'), ('unfixed', 'Editor will not fix'), ('falsepositive', 'False positive')], default='accepted', max_length=13),
        ),
    ]
